### ISSUE TITLE
[Crash]: Server crash on starting up.

### ISSUE THREAD

**Issue by evertn** [PlatinPython/ParticleGenerator#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Minecraft Version

1.20.1

### Forge Version

47.2.1

### Mod Version

1.2.0.0

### Description

It seems the mod is not suited for a dedicated server.

### Steps to reproduce

Restarting the server

### A link to the the debug.log, preferably on https://gist.github.com

https://gist.github.com/evertn/66064774bcc2290e9353d1004d692d8f

**Comment by PlatinPython** [comment]
Small mistake, will be fixed in 1.2.0.1, shouldn't take long for CurseForge to approve the file.

**Comment by evertn** [comment]
Great, thanks for the quick fix!
